### ISSUE TITLE
Unable to find a specification for `BRReuseQueue/Swift`

### ISSUE THREAD

**Issue by OutRunner** [brototyp/BRReusableQueue#2]
Hello,

I really like the look of your queue API, it's perfect for working with UIPageViewControllers but I can't seem to get Cocoapods to find the package. I'm getting the below error message:

[!] Unable to find a specification for `BRReuseQueue/Swift`

Is there something I'm doing wrong or has the package been removed from Cocoapods?

Cheers!

**Comment by brototyp** [comment]
Hi,

thats my fault. Please use this instead:
`pod 'BRReusableQueue/Swift'`

Best!

**Comment by OutRunner** [comment]
Thank you, you rock sir! :)

**Comment by brototyp** [comment]
You are welcome. Let me know it there is anything to improve

**Comment by OutRunner** [comment]
I think it works perfectly as it is, it was really easy to integrate with my UIPageViewController and my memory usage has plummeted as a result! If I do think of anything though I'll let you know. :)
